### GET all entries
GET http://localhost:3003/api/cafeLocations HTTP/1.1

###POST an entry
POST http://localhost:3003/api/cafeLocations HTTP/1.1
Content-Type: application/json

{

  "name": "KAVA coffee roasters",
      "address": "Max-Josef-Platz 23",
      "postcode": "83022",
      "city": "Rosenheim",
      "lat": "47.8563632",
      "lng": "	12.1282301"
}

